# Generated by Django 4.2.4 on 2023-08-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
