# Generated by Django 4.2.4 on 2023-08-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_favorite_favorite_unique_user_content_type_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='draft',
            field=models.TextField(choices=[('YES', 'В черновике'), ('NO', 'Опубликовано')], default='YES'),
        ),
    ]
